name: Vercel Deploy Hook
on:
  push:
    branches: [ "main" ]  # change if your prod branch is different
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          curl -X POST -d '{}' "${{ secrets.DEPLOY_HOOK_URL }}"
